### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by brayanmano** [Chem4Word/Version3#1]
When I click on draw molecule, a script error appears.
  What should I do?

**Comment by MikeWilliams-UK** [comment]
What operating system and version of word are you using?

**Comment by MikeWilliams-UK** [comment]
Please ensure you have IE 11 installed.

**Comment by MikeWilliams-UK** [comment]
Also if you are using server is please make sure IE enhanced security is off.

**Comment by brayanmano** [comment]
I'm used Windows 10 and office 2016

Em 18 de set de 2017 10:00 PM, "Mike Williams" <notifications@github.com<mailto:notifications@github.com>> escreveu:

What operating system and version of word are you using?

**Comment by MikeWilliams-UK** [comment]
The script error is happening when the embedded IE Control runs the JavaScript of the ChemDoodle Web editor.
You could try clearing the chem4word folder in your appdata\local folder

**Comment by MikeWilliams-UK** [comment]
Sorry closed in error

**Comment by brayanmano** [comment]
I did choice  in IE. But i install in computer with Windows 7 and compared to folders in appdata/user/local/

Miss the folder chemdoodleweb
The setup don't install This folder in Windows 10 build 16362


Em 18 de set de 2017 10:03 PM, "Mike Williams" <notifications@github.com<mailto:notifications@github.com>> escreveu:

Also if you are using server is please make sure IE enhanced security is off.

**Comment by MikeWilliams-UK** [comment]
I am confused now are you running Windows 7 or 10?
The code unzips the ChemDoodle Web folder to a sub folder of
appdata\chem4word.. folder when the edit button is clicked.
If something goes wrong during this process the 3rd party editor will not
run.

/Mike

**Comment by MikeWilliams-UK** [comment]
We have determined during our extensive testing of OS and word versions the
windows 7 MUST be fully patched.

/Mike

**Comment by brayanmano** [comment]
I'm used Windows 10

Em 18 de set de 2017 10:50 PM, "Mike Williams" <notifications@github.com<mailto:notifications@github.com>> escreveu:
I am confused now are you running Windows 7 or 10?
The code unzips the ChemDoodle Web folder to a sub folder of
appdata\chem4word.. folder when the edit button is clicked.
If something goes wrong during this process the 3rd party editor will not
run.

/Mike

**Comment by MikeWilliams-UK** [comment]
brayanmano,

I have checked the telemetry for Version3 and I can't see any errors being recorded.
Are you definatly using version 3, which you would have to have compiled yourself using Visual Studio 2015?

Please can you check in the folder C:\Users\{UserName}\AppData\Local\Chem4Word.V3
Can you please list the files in this folder.
does a folder "ChemDoodleWeb" exist? (I think you have already answered this)
does a folder "Telelmetry" exist?
If the folder Telemetry exists do log files exist inside it?
If so can you post one of them for when the JavaScript error occurs.

**Comment by MikeWilliams-UK** [comment]
brayanmano,

If you are using version 2 please post in the version 2 issues at https://github.com/Chem4Word/Version2/issues

For version 2 the log file is inside "C:\Users\{UserName}\AppData\Local\Chemistry Add-in for Word" and will be called "C4WLog.txt"

**Comment by MikeWilliams-UK** [comment]
brayanmano,

I can see some telemetry from your most recent attempts.
Have you now got the editor working? From the telemetry it appears that you have.

I can see that you are getting "Referência de objeto não definida para uma instância de um objeto.", which translates to "Object reference not set to an instance of an object."

The recorded stack trace is as follows
at Chem4Word.Helpers.CustomXmlPartHelper.GuidFromTag(String tag) na C:\Dev\vso\chem4word\C4W V.Next\Mike\Chem4Word.V3\Helpers\CustomXMLPartHelper.cs:line 47
at Chem4Word.Navigator.NavigatorViewModel.<>c__DisplayClass13_0.<OnPartAfterLoad>b__1(ContentControl cc) na C:\Dev\vso\chem4word\C4W V.Next\Mike\Chem4Word.V3\Navigator\NavigatorViewModel.cs:line 130
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
at Chem4Word.Navigator.NavigatorViewModel.OnPartAfterLoad(CustomXMLPart NewPart) na C:\Dev\vso\chem4word\C4W V.Next\Mike\Chem4Word.V3\Navigator\NavigatorViewModel.cs:line 128

We will look into this and let you know what our findings are.

**Comment by MikeWilliams-UK** [comment]
brayanmano,

It would also appear that you have version 2 and version 3 installed, which we know causes issues.

**Comment by MikeWilliams-UK** [comment]
brayanmano,

Where did you get the link to the v3 installers from?
We have not released this officially yet as it is still in very early beta stage!

**Comment by brayanmano** [comment]
Hi Mike,

I'm sorry for the late reply. I have the script error in version 2. But I posted issue in version 3. Sorry for this, I only seen this when you said.

Now, I am using version 3, installed with Visual Studio. I don't have same error more. I think that version 2 not compatible with my version Windows 10 (Pro insider build 16232) and the Office 2016.


Thanks.



____________________________________________________________________

Atenciosamente,

Brayan Jonas Mano Sousa.
Farmacêutico pela Universidade de Itaúna.
Pós-graduando em Farmácia Clínica - Faculdade Pitágoras.
Aluno no Mestrado em Ciências Farmacêuticas - UFSJ.
Telefone: 37 9 9138 – 0662
http://lattes.cnpq.br/6120507304609908





Enviado do Email para Windows 10

De: Mike Williams<mailto:notifications@github.com>
Enviado:quarta-feira, 27 de setembro de 2017 12:52
Para: Chem4Word/Version3<mailto:Version3@noreply.github.com>
Cc:brayanmano<mailto:brayanmano@live.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [Chem4Word/Version3] script error (#1)


brayanmano,

Where did you get the link to the v3 installers from?
We have not released this officially yet as it is still in very early beta stage!

**Comment by brayanmano** [comment]
Hi Mike,

I had this error yesterday when drawing some molecules, but today don't have any problems.



Thanks
____________________________________________________________________

Atenciosamente,

Brayan Jonas Mano Sousa.
Farmacêutico pela Universidade de Itaúna.
Pós-graduando em Farmácia Clínica - Faculdade Pitágoras.
Aluno no Mestrado em Ciências Farmacêuticas - UFSJ.
Telefone: 37 9 9138 – 0662

http://lattes.cnpq.br/6120507304609908





Enviado do Email para Windows 10

De: Mike Williams<mailto:notifications@github.com>
Enviado:quarta-feira, 27 de setembro de 2017 12:45
Para: Chem4Word/Version3<mailto:Version3@noreply.github.com>
Cc:brayanmano<mailto:brayanmano@live.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [Chem4Word/Version3] script error (#1)


brayanmano,

I can see some telemetry from your most recent attempts.
Have you now got the editor working? From the telemetry it appears that you have.

I can see that you are getting "Referência de objeto não definida para uma instância de um objeto.", which translates to "Object reference not set to an instance of an object."

The recorded stack trace is as follows
at Chem4Word.Helpers.CustomXmlPartHelper.GuidFromTag(String tag) na C:\Dev\vso\chem4word\C4W V.Next\Mike\Chem4Word.V3\Helpers\CustomXMLPartHelper.cs:line 47
at Chem4Word.Navigator.NavigatorViewModel.<>c__DisplayClass13_0.b__1(ContentControl cc) na C:\Dev\vso\chem4word\C4W V.Next\Mike\Chem4Word.V3\Navigator\NavigatorViewModel.cs:line 130
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext() at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
at Chem4Word.Navigator.NavigatorViewModel.OnPartAfterLoad(CustomXMLPart NewPart) na C:\Dev\vso\chem4word\C4W V.Next\Mike\Chem4Word.V3\Navigator\NavigatorViewModel.cs:line 128

We will look into this and let you know what our findings are.

**Comment by MikeWilliams-UK** [comment]
When using v3 you MUST let it convert the structures (it should ask you this when a file is opened)

**Comment by MikeWilliams-UK** [comment]
Please confirm that all is well with v3 and I can close this issue

**Comment by brayanmano** [comment]
Answering your previous questions: i I uninstalled version 2 before install version 3 with Visual Studio.

I converted all molecules, but I had this error when drawing the new molecules yesterday, but today, don't any erros.

I have a suggestion: Possibility of molecules have flat structure formula

Thanks.




____________________________________________________________________

Atenciosamente,

Brayan Jonas Mano Sousa.
Farmacêutico pela Universidade de Itaúna.
Pós-graduando em Farmácia Clínica - Faculdade Pitágoras.
Aluno no Mestrado em Ciências Farmacêuticas - UFSJ.
Telefone: 37 9 9138 – 0662

http://lattes.cnpq.br/6120507304609908





Enviado do Email para Windows 10

De: Mike Williams<mailto:notifications@github.com>
Enviado:quarta-feira, 27 de setembro de 2017 13:21
Para: Chem4Word/Version3<mailto:Version3@noreply.github.com>
Cc:brayanmano<mailto:brayanmano@live.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [Chem4Word/Version3] script error (#1)


When using v3 you MUST let it convert the structures (it should ask you this when a file is opened)

**Comment by brayanmano** [comment]
You can close error in version 3.

Obrigado
____________________________________________________________________

Atenciosamente,

Brayan Jonas Mano Sousa.
Farmacêutico pela Universidade de Itaúna.
Pós-graduando em Farmácia Clínica - Faculdade Pitágoras.
Aluno no Mestrado em Ciências Farmacêuticas - UFSJ.
Telefone: 37 9 9138 – 0662

http://lattes.cnpq.br/6120507304609908





Enviado do Email para Windows 10

De: Mike Williams<mailto:notifications@github.com>
Enviado:quarta-feira, 27 de setembro de 2017 13:22
Para: Chem4Word/Version3<mailto:Version3@noreply.github.com>
Cc:brayanmano<mailto:brayanmano@live.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [Chem4Word/Version3] script error (#1)


Please confirm that all is well with v3 and I can close this issue

**Comment by MikeWilliams-UK** [comment]
With V3 we encode data into the content controls tag, if this is empty (which could happen if a V2 chemistry did not convert properly) then these sort of errors will occur.

This will explain why you are seeing it working fine today with new structures or ones with correct tags.
