### ISSUE TITLE
Add an "R Groups" function

### ISSUE THREAD

**Issue by PlacidHysteria** [Chem4Word/Version3#18]
can someone add this? pls :D

**Comment by deadlyvices** [comment]
Do you mean being able to attach radical dots to individual atoms?

**Comment by PlacidHysteria** [comment]
No its errrr
In german its called "Organischer Rest" which could basically be any
organic structure which is able to connect to a specific base structure.
Like on the pics its mostly just referred as "R" or for multiple organic
rests "R'" or "R1"/"R2"

I googled for a translation and only found organic radicals which isnt
really the same.

But am sure u know what i mean :D

**Comment by deadlyvices** [comment]
There is a new editor in the next version of Chem4Word which will support these groups, along with pre-defined functional groups.

**Comment by MikeWilliams-UK** [comment]
We have now released Chem4Word 2020 (V3.1) for beta testing.
Please follow the instructions in https://github.com/Chem4Word/Version3-1/wiki/Beta-testing-Guide-for-Version-3.1-(Chem4Word-2020)
