### ISSUE TITLE
Scaling Issues on High Resolution Monitor

### ISSUE THREAD

**Issue by ForeverFloating** [Chem4Word/Version3#19]
**Describe the bug**
The add-on is scaled extremely small and it is hard for me to read clearly what the buttons on the top of the interface are.

**To Reproduce**
1. Change native screen resolution to 3840 x 2160 and Scale and Layout to 250%.
2. Click on the Chemistry Ribbon
3. Click on "Edit"
4. See screenshots below

**Expected behavior**
The menu and editing screen has consistent, readable scaling.

**Screenshots**
![Annotation 2019-12-10 200609](https://user-images.githubusercontent.com/30420818/70582505-bd151880-1b88-11ea-81a0-225f4f96ed87.png)
![Annotation 2019-12-10 200609 - Edit Labels](https://user-images.githubusercontent.com/30420818/70582512-c3a39000-1b88-11ea-8d7c-8c13a8cd5fb3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 1909
 - Microsoft Word Office 365 Version 1911

**Comment by MikeWilliams-UK** [comment]
This issue has now been moved into the correct repository

**Comment by MikeWilliams-UK** [comment]
@ForeverFloating please bear with us on this and if you can help with V3.1 beta testing this will be great.

**Comment by Wydna** [comment]
This is what the new version does with a monitor running at 150% scaling with 3840x2160 resolution:

![image](https://user-images.githubusercontent.com/3438413/71173314-45b34900-225a-11ea-84ab-620c614eb6ef.png)

**Comment by Wydna** [comment]
The new editor copes well at the same scaling and resolution:
![image](https://user-images.githubusercontent.com/3438413/71173473-bb1f1980-225a-11ea-8f0e-16cc68a2f17f.png)

**Comment by MikeWilliams-UK** [comment]
Thanks for the screenshots @Wydna

**Comment by MikeWilliams-UK** [comment]
We have now released Chem4Word 2020 (V3.1) for beta testing.
Please follow the instructions in https://github.com/Chem4Word/Version3-1/wiki/Beta-testing-Guide-for-Version-3.1-(Chem4Word-2020)
