### ISSUE TITLE
Erroneous  formula calculation (Caffeine)

### ISSUE THREAD

**Issue by theycallmevirgo** [Chem4Word/Version3#23]
**Describe the bug**
The plugin calculates an incorrect formula for caffeine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Chemistry tab
2. Click on Draw
3. Draw caffeine molecule 
4. Click on Edit Labels
**Expected behavior**
Chem4Word: ResolvedFormula should read C8H10N4O2
**Screenshots**

![image](https://user-images.githubusercontent.com/57016940/87894205-104d2480-ca10-11ea-82e2-63e6e6cbf3e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 enterpise
 - Word Version  2019 Professional 

**Additional context**

**Comment by deadlyvices** [comment]
That's because you're missing a nitrogen.  The 6 membered ring should have 2 nitrogen atoms.  You only have one.
![image](https://user-images.githubusercontent.com/10074162/87899479-3b079f00-ca49-11ea-9793-44dc9223209e.png)

**Comment by deadlyvices** [comment]
Closing as spurious
