### ISSUE TITLE
Silent Install Option

### ISSUE THREAD

**Issue by toadlife** [Chem4Word/Version3#3]
I work at a school and have Math faculty requesting this. It would be nice if there were a silent install option (or if there is one, it could be documented!), so that we could deploy this to all of our lab computers. 

For the time being, I'm deploying it via system center, but the users will have to click through the install themselves.

Thanks!

**Comment by MikeWilliams-UK** [comment]
Hi Paul,

In a NutShell
With logging
msiexec /i Chem4Word-Setup.3.0.10.Beta.10.msi /l*v setup10.log WINWORDVERSION=2013 /quiet

Without logging
msiexec /i Chem4Word-Setup.3.0.10.Beta.10.msi WINWORDVERSION=2013 /quiet

Latest version of msi can be downloaded from here
https://www.chem4word.co.uk/files3/

Change "WINWORDVERSION" setting as appropriate

Some of our users have already successfully distributed Chem4Word via SCCM.
I have worked through this with then in the following forum.
http://www.edugeek.net/forums/links/191722-your-chemists-chem4word.html

You should find useful information in there.
