### ISSUE TITLE
SMILES helper

### ISSUE THREAD

**Issue by ruska612** [Chem4Word/Version3#4]
Hi, I want to convert structures to SMILES format and show in Word. The problem was when I imported sdf structures from the Import icon, the 2D structures could not be shown as SMILES at the same time when I clicked the Show As icon. It seemed the imported structures  were deposited in the same object. Any advices would be helpful, thank you !

**Comment by MikeWilliams-UK** [comment]
If you want to display the 2D structure and smiles at the same time you will need to use the navigator to insert a linked copy of the structure displaying one as 2D and the other as smiles.
When the structure is edited both will be updated together.

**Comment by MikeWilliams-UK** [comment]
The software is operating correctly (as designed)

If you wish to display the textual label of both molecules
1. Import the sdf twice.
2. Edit the first one to remove cyclohexane
3. Edit the second one to remove benzene
4. Display both as invividual names
